#Script to deploy on the Render cloud platform
#specifies when this will run ie when a push/pull request is made

name: Node.js CI

on: 
  push: 
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: bounceapp/render-action@0.6.0
      with: 
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}}
        service-id: "srv-cioet95ph6elhbsepe80"
        retries: 20
        wait: 16000
        sleep: 30000

